### ISSUE TITLE
Add per grant prize badge to each project

### ISSUE THREAD

**Issue by AHReccese** [openscilab/openscilab.github.io#14]
#### Description
add a prize badge per grant for each project, something similar to this.
![image](https://github.com/openscilab/openscilab.github.io/assets/32750909/89122704-123b-49cd-aeb3-a8a3133a613c)

as of now, we have 6 badges:

1- Samila - IPFS Grant 2022
2- PyCM - PSF Development Grant 2022 
3- PyCM - Nlnet Grant 2022
4- PyCM - Trelis 2024
5- ART - PSF 2024
6- PyMilo - PSF Grant 2024

**Comment by AHReccese** [comment]
@F-Shahali 
Can you work on this?

**Comment by F-Shahali** [comment]
> @F-Shahali Can you work on this?

Sure, I will do it.
